version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=host.docker.internal  # 使用特殊的 DNS 名称来访问宿主机上的服务
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=webchat

volumes:
  dbdata:
